name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build application
      run: npm run build
      env:
        CI: false
     
    - name: Add version to build
      run: |
        BUILD_VERSION="${GITHUB_REF_NAME}-${GITHUB_SHA:0:7}"
        echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
        mv dist "build-${BUILD_VERSION}"

    - name: Zip the build
      run: zip -r build-${{ env.BUILD_VERSION }}.zip build-${{ env.BUILD_VERSION }}/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ env.BUILD_VERSION }}.zip
        path: build-${{ env.BUILD_VERSION }}.zip

    - name: Deploy to S3
      run: |
        aws s3 sync build-${{ env.BUILD_VERSION }}/ s3://admin.propertycontrol360.com/ --delete
      env:
        AWS_REGION: eu-central-1

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E30E1F8GTTME9A --paths "/*"
      env:
        AWS_REGION: eu-central-1
